name: ${project.name}
description: ${project.description}
main: ${project.bukkit.main}
version: ${project.version} (${git.commit.id.abbrev})
author: ${project.author}
softdepend: [Environment, Dewdrop]
depend: [PGM]
