name: MatchShare
description: ${description}
api-version: ${apiVersion}
main: ${mainClass}
version: ${version} (git-${commitHash})
author: ${author}
softdepend: [Environment, Dewdrop]
depend: [PGM, Community]
